name: Publicar reporte de cobertura

on:
  push:
    branches: [main]

env:
  DOTNET_VERSION: '8.0'

jobs:
  build-and-publish-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore & Build
        run: |
          dotnet restore PrimeService/Primes.Lib/Primes.Lib.csproj
          dotnet build PrimeService/Primes.Lib/Primes.Lib.csproj --configuration Release

      - name: Run tests and collect coverage
        run: |
          dotnet test PrimeService/Primes.Tests/Primes.Tests.csproj --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate coverage report
        run: |
          reportgenerator "-reports:PrimeService/Primes.Tests/TestResults/**/*.cobertura.xml" "-targetdir:coverage-report" -reporttypes:Html

      - name: Publish coverage report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-report
          keep_files: true