name: Generar NuGetPackage

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set version in .csproj
        run: sed -i.bak "s|<Version>.*</Version>|<Version>${VERSION}</Version>|" PrimeService/Primes.Lib/Primes.Lib.csproj

      - name: Clean sed backup file
        run: rm PrimeService/Primes.Lib/Primes.Lib.csproj.bak

      - name: Restore dependencies
        run: dotnet restore PrimeService/Primes.Lib/Primes.Lib.csproj

      - name: Build the project
        run: dotnet build PrimeService/Primes.Lib/Primes.Lib.csproj --configuration Release

      - name: Pack the NuGet package
        run: dotnet pack PrimeService/Primes.Lib/Primes.Lib.csproj -c Release

      - name: Publish package to GitHub Packages
        run: dotnet nuget push PrimeService/Primes.Lib/bin/Release/*.nupkg --skip-duplicate --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GH_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: "PrimeService/Primes.Lib/bin/Release/*.nupkg"